/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface KittyPartyWinnerDistributeEqualInterface
  extends utils.Interface {
  functions: {
    "getLength()": FunctionFragment;
    "getWinnerAtLocation(uint256)": FunctionFragment;
    "getWinners()": FunctionFragment;
    "initiateCheckWinner(uint256)": FunctionFragment;
    "prevWinnerIndexes(uint256)": FunctionFragment;
    "winnerIndexes(uint256)": FunctionFragment;
    "winnerStrategy()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getLength", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getWinnerAtLocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getWinners",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initiateCheckWinner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "prevWinnerIndexes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winnerIndexes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "winnerStrategy",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getLength", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getWinnerAtLocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getWinners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateCheckWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "prevWinnerIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnerIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnerStrategy",
    data: BytesLike
  ): Result;

  events: {};
}

export interface KittyPartyWinnerDistributeEqual extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KittyPartyWinnerDistributeEqualInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getWinners(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    prevWinnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    winnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    winnerStrategy(overrides?: CallOverrides): Promise<[number]>;
  };

  getLength(overrides?: CallOverrides): Promise<BigNumber>;

  getWinnerAtLocation(
    i: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getWinners(overrides?: CallOverrides): Promise<BigNumber[]>;

  initiateCheckWinner(
    _numberOfKittens: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  prevWinnerIndexes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  winnerIndexes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  winnerStrategy(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    getLength(overrides?: CallOverrides): Promise<BigNumber>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWinners(overrides?: CallOverrides): Promise<BigNumber[]>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    prevWinnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winnerStrategy(overrides?: CallOverrides): Promise<number>;
  };

  filters: {};

  estimateGas: {
    getLength(overrides?: CallOverrides): Promise<BigNumber>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getWinners(overrides?: CallOverrides): Promise<BigNumber>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    prevWinnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    winnerStrategy(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWinnerAtLocation(
      i: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getWinners(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initiateCheckWinner(
      _numberOfKittens: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    prevWinnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winnerIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winnerStrategy(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
